### ISSUE TITLE
Issue - 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by Elfertipp** [vishvvaw/Simple-Python-TwitterBot#5]
Hi,

I am all set, but after starting the Python program I get the following problem / error.

Running.... :)                    
'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

Please help

Regards,
ET

**Comment by vishwenga** [comment]
i am not sure but i have hunch that its caused by this line

` print("""\  `
` _____       _ _   _           _____ _____ _____`
`|_   _|_ _ _|_| |_| |_ ___ ___| __  |     |_   _|`
`  | | | | | | |  _|  _| -_|  _| __ -|  |  | | | `
`  |_| |_____|_|_| |_| |___|_| |_____|_____| |_|`
`             created by vishwenga`
`Running.... :)                    """)`

try removing that line.

`

**Comment by vishwenga** [comment]
ahhh yes thanks for informing me. 
Its is caused because i haven't implemented a way to get the whitelist account data from the text file.
I fixed it in the new commit.
